name: fluttie
description: Fluttie allows you to easily display stunning Lottie animations in flutter.
version: 0.3.1
author: simolus3 <simolus3@gmail.com>
homepage: https://github.com/simolus3/fluttie

environment:
  sdk: ">=1.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: de.simolus3.fluttie
    pluginClass: FluttiePlugin
